name: Main Workflow

on:
  push:
    branches:
      - main

jobs:
  auto_bump:
    runs-on: ubuntu-latest

    permissions:
      contents: write

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Conventional Changelog Action
        uses: TriPSs/conventional-changelog-action@v3
        with:
            github-token: ${{ secrets.github_token }}
            version-file: './version.toml'
